- name: Add Falco GPG key
  apt_key:
    url: https://download.falco.org/packages/deb/falco.key
    state: present

- name: Add Falco repository
  apt_repository:
    repo: "deb https://download.falco.org/packages/deb stable main"
    state: present

- name: Install Falco
  apt:
    name: falco
    state: present
    update_cache: yes

- name: Ensure Falco is running
  systemd:
    name: falco
    state: started
    enabled: true
